### ISSUE TITLE
PHP7.2 missing mcrypt

### ISSUE THREAD

**Issue by lucien144** [lucien144/lemp-stack#10]
https://github.com/lucien144/lemp-stack/pull/9#issuecomment-357988676

**Comment by jonathan-bird** [comment]
Shouldn't be using mcrypt anymore. I was looking at this the other day. Bcrypt is what's generally used in new versions of php - 7.x

Laravel dropped mcrypt support as well in their new versions.

**Comment by lucien144** [comment]
I see, mcrypt has been deprecated in PHP7.1 and removed in PHP7.2. I'll remove this from the tutorial and replace it by [OpenSSL](http://php.net/manual/en/function.openssl-encrypt.php).

Thanks @jonathan-bird !
