### ISSUE TITLE
domain name tqode.com no more working

### ISSUE THREAD

**Issue by JefferyHus** [lucien144/lemp-stack#11]
After I completed the tutorial my domain name started to redirect to www.tqode.com and I see no response at all, and even if I hit the ip http://178.62.76.82/ I get 403 error, if you can help please.

**Comment by lucien144** [comment]
Hi @JefferyHus,
I can see the domain is working now. Did you manage to find the issue? Can I close this ticket?

Thanks.

**Comment by JefferyHus** [comment]
No i just reinstalled nginx, but didn't use this tutorials, I couldn't find where the issue remains.

**Comment by lucien144** [comment]
Interesting... I'm running this on several servers without any issue. Anyway, closing this now. Thanks.
